before_script:
    - module load gfortran/6.2
    - module load cmake/3.6.1

stages:
    - build
    - test
    - deploy

serial_build:
    stage: build
    script:
        - mkdir ser_build
        - cd ser_build
        - FC=gfortran cmake ..
        - make -j
    artifacts:
        paths:
        - ./*

parallel_build:
    stage: build
    script:
        - mkdir par_build
        - cd par_build
        - FC=gfortran cmake ..
        - make -j
    artifacts:
        paths:
        - ./*

ser_test_gauss3d:
    stage: test
    script:
        - ./ser_build/tests/gauss3d

par_test_gauss3d:
    stage: test
    script:
        - ./par_build/tests/gauss3d

ser_test_sedov3d:
    stage: test
    script:
        - ./ser_build/tests/sedov3d

par_test_sedov3d:
    stage: test
    script:
        - ./par_build/tests/sedov3d
